### ISSUE TITLE
Add a title under each menu icon?

### ISSUE THREAD

**Issue by GitWillMeng** [Ramotion/circle-menu#45] opened 2017-10-24 21:33 UTC
Hi,
I am wondering if there is any way that I can add a text label (or title) underneath each popup menu icon?
Thanks

**Comment by Mahan3340** [comment] 2017-10-25 05:05
+1

**Comment by tache** [comment] 2018-01-04 11:10
Yes - you have full access to the UIButton ... 

within ...  
`func circleMenu(_ circleMenu: CircleMenu, willDisplay button: UIButton, atIndex: Int) { ... }`

do something like ...

```
button.setTitle("button \(atIndex)", for: .normal)
button.setTitleColor(.red, for: .normal)
button.titleLabel?.font = UIFont(name: "Helvetica Neue", size: 12)
button.contentVerticalAlignment = .fill
button.contentHorizontalAlignment = .left
button.titleEdgeInsets = UIEdgeInsets(top: 80.0, left: -120.0, bottom: 5.0, right: 5.0)
```

**Comment by 0ber** [comment] 2018-01-18 12:21
Duplicate of #30

**Closed as completed** 2018-01-22 08:52 UTC
Labels: question
